// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxuR6Y4V_wF0kAkTft1NbiCrEBNqu0OWQ',
    appId: '1:994847387400:web:76726a7386dad7469f46bd',
    messagingSenderId: '994847387400',
    projectId: 'journalists-syndicate',
    authDomain: 'journalists-syndicate.firebaseapp.com',
    storageBucket: 'journalists-syndicate.firebasestorage.app',
    measurementId: 'G-KVNVVB2PYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9fMk_x-dLEa_I3821AcRja9q4SBwWQ3M',
    appId: '1:994847387400:android:dea0f310b7602e609f46bd',
    messagingSenderId: '994847387400',
    projectId: 'journalists-syndicate',
    storageBucket: 'journalists-syndicate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0XENVt81MBmKexcqkViWE9knG19q8_WM',
    appId: '1:994847387400:ios:9c3bcde3f07bdbe69f46bd',
    messagingSenderId: '994847387400',
    projectId: 'journalists-syndicate',
    storageBucket: 'journalists-syndicate.firebasestorage.app',
    iosBundleId: 'com.pjs.pjsportal.pjsPortal',
  );
}
